version: 2.1
jobs:
  release:
    docker:
      - image: paulmarsicloud/hexo-aws:1.5
    working_directory: ~/hexo-cloudonmymindblog
    steps:
      - checkout
      - run:
          name: Force theme download
          command: git clone https://github.com/paulmarsicloud/hexo-theme-cactus themes/cactus
      - run:
          name: Generate static website
          command: hexo generate
      - run:
          name: Push to S3 bucket
          command: hexo deploy

workflows:
    version: 2
    build_and_deploy:
      jobs:
        - release